name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: ["bug", "new"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: dropdown
  attributes:
    label: Nature of Your Project
    description: Have you encountered the issue in the context of a JavaScript or TypeScript project?
    default: 0
    multiple: true
    options:
      - JavaScript
      - TypeScript
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: |
      Steps to reproduce the behavior.
      Tip: You can add CDS code in code fences:
      <pre>
      ```cds
      entity Foo {
        bar: String;
        baz: Integer;
      }
      ```
      </pre>
    placeholder: |
      1. In this environment...
      2. With this config...
      3. With this sample model...
      4. Run '...'/ Do...
      5. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      You can acquire the input for the cds-field by running `cds v -i`.
      The version of cds-typer can be acquired by running `npx cds-typer --version`.
    value: |
        - **OS**:
        - **Node**:
        - **npm**:
        - **cds-typer**: 
        - **cds**:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Repository Containing a Minimal Reproducible Example
    placeholder: https://github.com/my/repository
    description: |
      Do you have a sample repository where we can observe the reported behaviour? Please include the relevant branch.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false