---
name: 💡 Feature Request
description: Request a missing feature
title: "[FEATURE] <title>"
labels: ["feature_request", "new"]
body:
  - type: textarea
    attributes:
      label: Description
      description: |
        A concise description of the feature you're interested in. If possible include use cases, pointers to CAPire, and how it would benefit this tool and its users.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested Solution
      description: |
        Describe your proposed solution. A clear and concise description of what you want to happen. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: |
        Describe alternatives you can see for this problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false